# Generated by Django 5.2.17 on 2026-09-01 23:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
                ('author_role', models.CharField(max_length=50)),
                ('author_email', models.EmailField(max_length=100)),
                ('author_git_user', models.CharField(max_length=50)),
                ('author_country', models.CharField(max_length=50)),
                ('author_photo', models.ImageField(upload_to=None)),
                ('author_intro', models.TextField()),
                ('author_resume', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('event', models.TextField()),
                ('skills', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='academic_participations', to='api.authorinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masters_study', models.CharField(max_length=100)),
                ('masters_university', models.CharField(max_length=100)),
                ('masters_graduation_date', models.DateField()),
                ('bachelor_study', models.CharField(max_length=100)),
                ('bachelor_university', models.CharField(max_length=100)),
                ('bachelor_graduation_date', models.DateField()),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='api.authorinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertiseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(max_length=100)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to='api.authorinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertiseTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_url', models.URLField()),
                ('tool_image', models.FileField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpg'])])),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.expertisecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.authorinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('participants', models.CharField(max_length=250)),
                ('role', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.URLField()),
                ('journal', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='api.authorinfo')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='api.authorinfo')),
            ],
        ),
    ]
