# Generated by Django 5.2.17 on 2026-09-02 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicparticipation',
            options={'verbose_name_plural': 'academic participation'},
        ),
        migrations.AlterModelOptions(
            name='authorinfo',
            options={'verbose_name_plural': 'author info'},
        ),
        migrations.AlterModelOptions(
            name='authorstudies',
            options={'verbose_name_plural': 'author study'},
        ),
        migrations.AlterModelOptions(
            name='expertisecategory',
            options={'verbose_name_plural': 'expertise category'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish'], 'verbose_name_plural': 'post'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'project'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name_plural': 'publication'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name_plural': 'work experience'},
        ),
    ]
