# Generated by Django 5.2.17 on 2026-09-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_academicparticipation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='sample', upload_to=None),
            preserve_default=False,
        ),
    ]
