# Generated by Django 5.2.17 on 2026-09-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(max_length=300),
        ),
    ]
