# Generated by Django 5.2.17 on 2026-09-09 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_workexperience_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorinfo',
            name='author_role',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(choices=[('BS', "Bachelor's"), ('MS', "Master's"), ('PHD', 'PhD'), ('CERT', 'Certificate')], max_length=10)),
                ('field_of_study', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='api.authorinfo')),
            ],
            options={
                'verbose_name_plural': 'degrees',
                'ordering': ['-graduation_date'],
            },
        ),
        migrations.DeleteModel(
            name='AuthorStudies',
        ),
    ]
