# Generated by Django 5.2.17 on 2026-09-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_authorinfo_author_role_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='author_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.authorinfo')),
            ],
        ),
    ]
